version: "3.7"

services: 

  ansible:
    build:
      context: ./
      dockerfile: Dockerfile-ansible-python
    image: rayniel95/ansible:1.1-alpine-plus-python
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./:/ansible"
    command: ansible-playbook -i 127.0.0.1 ./ansible/playbook.yaml
    container_name: ansible
# FIXME - poner el localhost directo en el inventario de la imagen