- name: create_image
  docker_image:
    build:
      path: "{{ image_path }}"
      pull: false
      # dockerfile: in case dockerfile name change
    name: rayniel95/cmsnode
    source: build

- name: create_network
  docker_network:
    name: ray_net
# FIXME - por alguna razon esta haciendo attach a otra red, se deben purgar todas las
# redes primero
- name: create_containers
  docker_container:
    image: rayniel95/cmsnode
    name: "node_{{ index }}"
    networks:
      - name: ray_net
    ports:
      - "500{{ index }}: 5000"
  loop: "{{ range(cantity_containers)|list }}"
  loop_control:
    pause: "{{ wait_time }}"
    index_var: index
