- name: create_image
  docker_image:
    build:
      path: "{{ image_path }}"
      pull: false
      # dockerfile: in case dockerfile name change
    name: rayniel95/cmsnode
    source: build

- name: create_network
  docker_network:
    name: ray_net

- name: create_containers
  docker_container:
    image: rayniel95/cmsnode
    name: "node_{{ index }}"
    networks_cli_compatible: true
    networks:
      - name: ray_net
    published_ports:
      - "500{{ index }}:5000"
  loop: "{{ range(cantity_containers)|list }}"
  loop_control:
    pause: "{{ wait_time }}"
    index_var: index
