- hosts: localhost # FIXME - agregar al inventario solo el localhost
  roles:
    - role: start_containers
      vars:
        wait_time: 120
        cantity_containers: 5
        image_path: /ansible/ # FIXME - fix this path, must be relative
     